export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const FETCH_PROFILE = "FETCHING_PROFILE";

export const FETCHING_COURSE_USER = "FETCHING_COURSE_USER";
export const FETCH_COURSE_USER_DONE = "FETCH_COURSE_USER_DONE";

export const FETCHING_LESSON = "FETCHING_LESSON";
export const FETCH_LESSON_DONE = "FETCH_LESSON_DONE";

export const FETCHING_REVENUE = "FETCHING_REVENUE";
export const FETCH_REVENUE_DONE = "FETCH_REVENUE_DONE";
export const FETCH_REVENUE_DEBT_DONE = "FETCH_REVENUE_DEBT_DONE";

export const FETCHING_STUDENT = "FETCHING_STUDENT";
export const FETCH_STUDENT_DONE = "FETCH_STUDENT_DONE";

export const FETCHING_VOUCHER = "FETCHING_VOUCHER";
export const FETCH_VOUCHER_DONE = "FETCH_VOUCHER_DONE";

export const FETCHING_BILLING = "FETCHING_BILLING";
export const FETCH_BILLING_DONE = "FETCH_BILLING_DONE";
export const FETCHING_ORDERS = "FETCHING_ORDERS";
export const FETCH_ORDERS_DONE = "FETCH_ORDERS_DONE";

export const FETCHING_ORDERS_MENTOR = "FETCHING_ORDERS_MENTOR";
export const FETCH_ORDERS_MENTOR_DONE = "FETCH_ORDERS_MENTOR_DONE";

export const FETCHING_ROOM = "FETCHING_ROOM";
export const FETCH_ROOM_DONE = "FETCH_ROOM_DONE";
export const FETCHING_ROOM_USER = "FETCHING_ROOM_USER";
export const FETCH_ROOM_USER_DONE = "FETCH_ROOM_USER_DONE";
export const FETCHING_ROOM_MENTOR = "FETCHING_ROOM_MENTOR";
export const FETCH_ROOM_MENTOR_DONE = "FETCH_ROOM_MENTOR_DONE";

export const FETCHING_ROLES = "FETCHING_ROLES";
export const FETCH_ROLES_DONE = "FETCH_ROLES_DONE";

export const FETCHING_APIS = "FETCHING_APIS";
export const FETCH_APIS_DONE = "FETCH_APIS_DONE";

export const FETCHING_SESSIONS = "FETCHING_SESSIONS";
export const FETCH_SESSIONS_DONE = "FETCH_SESSIONS_DONE";

export const FETCHING_USERS = "FETCHING_USERS";
export const FETCH_USERS_DONE = "FETCH_USERS_DONE";

export const FETCHING_MENTOR = "FETCHING_MENTOR";
export const FETCH_MENTOR_DONE = "FETCH_MENTOR_DONE";

export const FETCHING_MATERIALS = "FETCHING_MATERIALS";
export const FETCH_MATERIALS_DONE = "FETCH_MATERIALS_DONE";

export const FETCHING_ASSIGNMENT = "FETCHING_ASSIGNMENT";
export const FETCH_ASSIGNMENT_DONE = "FETCH_ASSIGNMENT_DONE";

export const FETCHING_ASSET = "FETCHING_ASSET";
export const FETCH_ASSET_DONE = "FETCH_ASSET_DONE";

export const FETCHING_USER_LESSON = "FETCHING_USER_LESSON";
export const FETCH_USER_LESSON_DONE = "FETCH_USER_LESSON_DONE";

export const FETCHING_SLIDE = "FETCHING_SLIDE";
export const FETCH_SLIDE_DONE = "FETCH_SLIDE_DONE";

export const FETCHING_EXAMS = "FETCHING_EXAMS";
export const FETCH_EXAMS_DONE = "FETCH_EXAMS_DONE";
export const FETCHING_QUIZZES = "FETCHING_QUIZZES";
export const FETCH_QUIZZES_DONE = "FETCH_QUIZZES_DONE";


// Trung tâm
export const FETCHING_CENTER = "FETCHING_CENTER";
export const FETCH_CENTER_DONE = "FETCH_CENTER_DONE";
// lớp học
export const FETCHING_CLASSES = "FETCHING_CLASSES";
export const FETCH_CLASSES_DONE = "FETCH_CLASSES_DONE";
export const FETCHING_CLASSROOM = "FETCHING_CLASSROOM";
export const FETCH_CLASSROOM_DONE = "FETCH_CLASSROOM_DONE";
export const FETCHING_COURSE = "FETCHING_COURSE";
export const FETCH_COURSE_DONE = "FETCH_COURSE_DONE";